### ISSUE TITLE
我导入到AS后，Library库资源文件冲突。

### ISSUE THREAD

**Issue by sendtion** [JZXiang/TimePickerDialog#11]
我导入到AS后，Library库资源文件冲突。
Library库中的String资源文件有个app_name，跟我项目中的app_name冲突，导致我的APP名称变成了Library，请问这个怎么解决呢？

**Comment by lxygithub** [comment]
哈哈  同样的问题 让作者把他的appname删除了就可以了吧

**Comment by JZXiang** [comment]
添加gradle依赖没有这个问题，下个版本，我把library的app_name的字段名字改下。

**Comment by lxygithub** [comment]
作者您好 ，弱弱的问下，添加gradle依赖指的是在 app/build.gradle文件的dependencies下面添加
 compile 'com.jzxiang.pickerview:TimePickerDialog:0.9.9' 这个嘛？我明明就是这样添加的，如果问题太低级，请尽情嘲笑我吧，但是希望能帮忙解惑

**Comment by sendtion** [comment]
@JZXiang 就是添加的gradle依赖，就是这个问题，望改进，尽快哦

**Comment by JZXiang** [comment]
@lxygithub 是的

**Comment by JZXiang** [comment]
@sendtion gradle依赖也有这个问题吗？我项目中也用了，没发现有这个问题呀，Android系统版本是？

**Comment by JZXiang** [comment]
demo中也是这么用的，也没发现有这个问题

**Comment by sendtion** [comment]
@JZXiang Android6.0版本，我暂时用Activity的label给覆盖了，但是在应用程序列表里还是显示的Library，真是奇怪了。为了从根本上解决问题，还是麻烦修改或者去掉app_name吧，感谢！

**Comment by JZXiang** [comment]
好的

**Comment by lxygithub** [comment]
我是android5.0 奇怪在android4.4中没有发现

**Comment by JZXiang** [comment]
已删

**Comment by sendtion** [comment]
@JZXiang 非常感谢！
