### ISSUE TITLE
重大bug

### ISSUE THREAD

**Issue by gsc1234567890woshishui** [JZXiang/TimePickerDialog#24]
怎么修改默认时间你默认是2015年，我如何设置成1990年

**Comment by Developmc** [comment]
long tenYears = 10L * 365 * 1000 * 60 * 60 * 24L;
setMinMillseconds(System.currentTimeMillis()-tenYears)  //设置最小时间
setMaxMillseconds(System.currentTimeMillis() + tenYears)  //设置最大时间
