### ISSUE TITLE
可以设置显示在中间吗

### ISSUE THREAD

**Issue by 179098051** [JZXiang/TimePickerDialog#38]

**Comment by fengxin0210fx** [comment]
同问

**Comment by JZXiang** [comment]
可以自行修改布局[timepicker_layout](https://github.com/JZXiang/TimePickerDialog/blob/master/TimePickerDialog/src/main/res/layout/timepicker_layout.xml)

**Comment by fengxin0210fx** [comment]
谢谢，知道了，我把代码下载下来，修改修改。



---原始邮件---
发件人: "JiaoZhengXiang"<notifications@github.com&gt;
发送时间: 2020年1月3日(周五) 中午11:30
收件人: "JZXiang/TimePickerDialog"<TimePickerDialog@noreply.github.com&gt;;
抄送: "fengxin0210fx"<1638627187@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [JZXiang/TimePickerDialog] 可以设置显示在中间吗 (#38)



可以自行修改布局timepicker_layout
