### ISSUE TITLE
为什么不可以设置过去的时间呢？

### ISSUE THREAD

**Issue by sendtion** [JZXiang/TimePickerDialog#4]
为什么不可以设置过去的时间呢？
现在只能设置当前时间以后的时间，希望后续版本加上过去时间的支持！

**Comment by JZXiang** [comment]
设置过去时间是什么意思

**Comment by Zke1ev3n** [comment]
就是设置以前的时间，比如用来选择生日，用了之后才发现不行。。。

**Comment by JZXiang** [comment]
是可以的，默认是当前时间，setMinMillseconds这个接口可以设置最小时间，最大时间是2050年。

**Comment by sendtion** [comment]
原来如此，感谢！
