### ISSUE TITLE
建议添加选取的时间为月初或月末的选项

### ISSUE THREAD

**Issue by 2391645784** [JZXiang/TimePickerDialog#43]
如题

**Comment by JZXiang** [comment]
默认时间选项为月初或者月末？

**Comment by 2391645784** [comment]
选中的时间为月末 比如说选中后得到的是1月31日的毫秒数这样子。。。

**Comment by 2391645784** [comment]
默认时间默认为月初就好了

**Comment by JZXiang** [comment]
选中后回调的时间戳么

**Comment by 2391645784** [comment]
嗯嗯

**Comment by 2391645784** [comment]
时间有范围限制吗？ 只能选前后50年？

**Comment by JZXiang** [comment]
` .setMinMillseconds(System.currentTimeMillis())
                                    .setMaxMillseconds(System.currentTimeMillis() + tenYears)
                                    .setCurrentMillseconds(System.currentTimeMillis())`
这些配置接口应该可以满足你的要求，回调后的时间戳精确到毫秒，暴漏出去处理比较好

**Comment by 2391645784** [comment]
这个有试过了 最大不会超过50年。。。。

**Comment by JZXiang** [comment]
将最大值和最小值都设置后，是没问题的，不会走默认值（50年）

**Comment by 2391645784** [comment]
这样啊 我再试试 3Q
