### ISSUE TITLE
滑动到最后 textview不显示?

### ISSUE THREAD

**Issue by 0nlying** [JZXiang/TimePickerDialog#48]
能不能继续显示? 或者 有没有办法关闭这种越界的滑动 比如第一个或者最后一个就没法再滑动了

**Comment by JZXiang** [comment]
可以参考demo设置循环显示

**Comment by JZXiang** [comment]
`setCyclic(true)`

**Comment by 0nlying** [comment]
需求是不要循环啊 OMG..... 可否告知哪里关闭这个越界呢  或者不要越界一半的时候消失也好呀

**Comment by 0nlying** [comment]
搞定了- -....
