### ISSUE TITLE
Error:Could not find property 'PROJ_GROUP' on project ':TimePickerDialog'.

### ISSUE THREAD

**Issue by Ocean0227** [JZXiang/TimePickerDialog#49]
导入AS后，gradle构建过程中报错

**Comment by aaryan1** [comment]
i also  got the same issue

**Comment by JZXiang** [comment]
可以忽略掉，这个是用于jcenter上传的变量，注释掉相关地方

**Comment by aaryan1** [comment]
sorry please write  in English.

**Comment by aaryan1** [comment]
how can we set time in 12 hour format ??

**Comment by Linfeng1028** [comment]
> 可以忽略掉，这个是用于jcenter上传的变量，注释掉相关地方

我也遇到这个问题了，注释了一个就还会有另一个相关的跳出来

**Comment by JZXiang** [comment]
无关使用都可以注释掉
