### ISSUE TITLE
所有title的默认值是空

### ISSUE THREAD

**Issue by zhangchaoxu** [JZXiang/TimePickerDialog#5]
上一个版本中加入了各种title的自定义，如setCancelStringId、setTitleStringId等。
但是这些title的默认值现在都变成空，必须要赋值。
建议给一个默认值。这样就不需要每次调用都给这些title string赋值。

Thanks

**Comment by JZXiang** [comment]
我会查看此问题并尽快修复，thanks.

**Comment by zhangchaoxu** [comment]
我看到DefaultConfig中有静态init方法，不过没调用。

thank you

**Comment by JZXiang** [comment]
已修复。 @zhangchaoxu

**Comment by zhangchaoxu** [comment]
https://github.com/donglua/PhotoPicker

**Comment by zhangchaoxu** [comment]
发现已经有默认文字，但是都是英文的，即使操作系统语音是中文，默认显示的语言还是英文的。

**Comment by JZXiang** [comment]
有接口可以设置.
` java 
.setCancelStringId("Cancel")
                                    .setSureStringId("Sure")
                                    .setTitleStringId("TimePicker")
                                    .setYearText("Year")
                                    .setMonthText("Month")
                                    .setDayText("Day")
                                    .setHourText("Hour")
                                    .setMinuteText("Minute")
`

**Comment by JZXiang** [comment]
有接口可以设置.
`  .setCancelStringId("Cancel") 
.setSureStringId("Sure") 
.setTitleStringId("TimePicker")
 .setYearText("Year") 
.setMonthText("Month")
 .setDayText("Day") 
.setHourText("Hour")
 .setMinuteText("Minute")  `

**Comment by zhangchaoxu** [comment]
got it
