### ISSUE TITLE
英文环境

### ISSUE THREAD

**Issue by a8453770** [JZXiang/TimePickerDialog#54]
请问支持英文环境的日月年显示格式嘛

**Comment by JZXiang** [comment]
.setCancelStringId("Cancel")
                                    .setSureStringId("Sure")
                                    .setTitleStringId("TimePicker")
                                    .setYearText("Year")
                                    .setMonthText("Month")
                                    .setDayText("Day")
                                    .setHourText("Hour")
                                    .setMinuteText("Minute")
