### ISSUE TITLE
setMinMillseconds建议能控制到分钟

### ISSUE THREAD

**Issue by zhangchaoxu** [JZXiang/TimePickerDialog#6]
现在设置setMinMillseconds后，默认的小时数是min值+1.无法控制到分钟。

比如我设置setMinMillseconds为12:30分，跳出来的dialog是从13:00开始的，无法选择到12:30-13：00之间的时间。

Thanks

**Comment by JZXiang** [comment]
确实是这样的，会自动回累计到下个小时。我想业务场景没有需要精确到选择分钟的吧

**Comment by zhangchaoxu** [comment]
其实精确到分钟的业务场景还是满常见的，如果是只需要精确到小时，也就没必要显示分钟。
如果方便，烦请加上这个feature。

Thanks

**Comment by JZXiang** [comment]
最新的版本精确到分钟了。 @zhangchaoxu

**Comment by zhangchaoxu** [comment]
Thanks
