### ISSUE TITLE
Min milliseconds works fine but max milliseconds does not work

### ISSUE THREAD

**Issue by seongminchoob** [JZXiang/TimePickerDialog#62]
<img width="246" alt="screen shot 2018-11-07 at 10 27 09 am" src="https://user-images.githubusercontent.com/35505959/48104630-b9bda800-e277-11e8-97de-a27108efb4ab.png">

I set min to 10 max to 12 h 
Min is working fine but Max does not set the boundary

**Comment by JZXiang** [comment]
.setMinMillseconds(System.currentTimeMillis())
  .setMaxMillseconds(System.currentTimeMillis() + tenYears)


Please check your timemillseconds.
