### ISSUE TITLE
Can Migrate to AndroidX (能升级到AndroidX版本吗)

### ISSUE THREAD

**Issue by apple2360541** [JZXiang/TimePickerDialog#63]
I have used your library in my project, but i want to migate to AndroidX,while your library is using support, now many project is migrate to androidX,Do you have any plan to migrate to AndroidX 项目中有使用你的库，但是现在都往AndroidX迁移了，你有没有迁移到AndroidX的计划？

**Comment by JZXiang** [comment]
android studio 可以自动升级到androidX版本

**Comment by apple2360541** [comment]
你的库用了support包的东西，我迁移到AndroidX，通过gradle的依赖方式编译不了，只能下载library依赖才能迁移

**Comment by JZXiang** [comment]
https://www.jianshu.com/p/5ef065abfe07
可参考此链接进行升级
