### ISSUE TITLE
Please provide english version

### ISSUE THREAD

**Issue by RayVaniya** [JZXiang/TimePickerDialog#64]
There is Chinese fonts besides Hours and minutes.
![image](https://user-images.githubusercontent.com/25399436/69802745-3d8a5f80-1200-11ea-951a-b7d5bc161aad.png)

**Comment by JZXiang** [comment]
`  mDialogAll = new TimePickerDialog.Builder()
                                    .setCallBack(this)
                                    .setCancelStringId("Cancel")
                                    .setSureStringId("Sure")
                                    .setTitleStringId("TimePicker")
                                    .setYearText("Year")
                                    .setMonthText("Month")
                                    .setDayText("Day")
                                    .setHourText("Hour")
                                    .setMinuteText("Minute")
                                    .setCyclic(false)
                                    .setMinMillseconds(System.currentTimeMillis())
                                    .setMaxMillseconds(System.currentTimeMillis() + tenYears)
                                    .setCurrentMillseconds(System.currentTimeMillis())
                                    .setThemeColor(getResources().getColor(R.color.timepicker_dialog_bg))
                                    .setType(Type.ALL)
                                    .setWheelItemTextNormalColor(getResources().getColor(R.color.timetimepicker_default_text_color))
                                    .setWheelItemTextSelectorColor(getResources().getColor(R.color.timepicker_toolbar_bg))
                                    .setWheelItemTextSize(12)
                                    .build();`
`.setYearText("Year")
                                    .setMonthText("Month")
                                    .setDayText("Day")
                                    .setHourText("Hour")
                                    .setMinuteText("Minute")`

**Comment by JZXiang** [comment]
.setYearText("Year")
 .setMonthText("Month")
.setDayText("Day")
.setHourText("Hour")
.setMinuteText("Minute")
