### ISSUE TITLE
How to Imoprt into AS

### ISSUE THREAD

**Issue by AndroidNerd** [JZXiang/TimePickerDialog#8]
how to import this project in to android studio?I get error:could not find property 'PROJ_GROUP' on project ':TimepickerDialog'.

**Comment by JZXiang** [comment]
You can use the jcenter.Add 'compile 'com.jzxiang.pickerview:TimePickerDialog:0.9.3''

**Comment by AndroidNerd** [comment]
I know that,But if I want to use it in eclipse IDE,and I have no idea how to do it.and thx you anyway

**Comment by AndroidNerd** [comment]
what function doese you bintray file that in the path:TimePickerDialog/
error shows could not find it's PROJ_GROUP

**Comment by JZXiang** [comment]
You can delete these error codes.The error codes is jceter config.

**Comment by JZXiang** [comment]
I have not provided the eclipse version.

**Comment by AndroidNerd** [comment]
I tried that and It worked. thx u

**Comment by JZXiang** [comment]
You're welcome.
